# Generated by Django 4.0.4 on 2022-04-19 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('cpf_cnpj', models.CharField(max_length=18, unique=True, verbose_name='CPF/CNPJ')),
            ],
            options={
                'verbose_name': 'Client',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_code', models.CharField(max_length=20, verbose_name='Agency Code')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agencies', to='bank.bank', verbose_name='Bank')),
            ],
            options={
                'verbose_name': 'Agency',
                'ordering': ['name'],
                'unique_together': {('agency_code', 'bank')},
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=80, verbose_name='Number')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Balance')),
                ('type', models.CharField(choices=[('PHYSICAL', 'Physical person'), ('LEGAL', 'Legal person')], max_length=15, verbose_name='Type')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='bank.agency', verbose_name='Agency')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='bank.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Account',
                'ordering': ['number'],
                'unique_together': {('client', 'type', 'agency')},
            },
        ),
    ]
