name: Build-Test

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build - Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run docker-compose
      run: docker-compose up -d

    - name: Wait to service db starts
      run: sleep 20

    - name: Run tests
      run: docker exec -i bank-django-nuxt3-api /bin/bash -c "python manage.py test"
      