name: Build-Test

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build - Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run docker-compose
      run: docker-compose -f docker-compose.prod.yaml up -d

    - name: Run tests and collect coverage
      run: docker exec -i bank-django-nuxt3-api /bin/bash -c "coverage run --source='.' manage.py test"

    - name: Generate coverage to xml file
      run: docker exec -i bank-django-nuxt3-api /bin/bash -c "coverage xml -o coverage.xml"

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      